In [95]:
setups = [{
    "model":"qwen3:4b",
    "prompt":"V11",
    "force_no_think": True,
},
{
    "model":"qwen3:4b",
    "prompt":"V18",
    "force_no_think": True,
},
{
    "model":"llama3.2:3b",
    "prompt":"V11"
},
{
    "model":"llama3.2:3b",
    "prompt":"V18"
},

{
    "model":"mistral",
    "prompt":"V11"    
},
{
    "model":"mistral",
    "prompt":"V18"    
},

{
    "model":"gemma3:4b",
    "prompt":"V11"    
},
{
    "model":"gemma3:4b",
    "prompt":"V18"
},
{
    "model":"gemma3n:e4b",
    "prompt":"V11"    
},
{
    "model":"gemma3n:e4b",
    "prompt":"V18",    
},
{
    "model":"llama3.2:1b",
    "prompt":"V11"
},
{
    "model":"gemma3:1b",
    "prompt":"V11"
},
{
    "model":"qwen3:1.7b",
    "prompt":"V11",
    "force_no_think": False,
},
{
    "model":"qwen3:4b",
    "prompt":"V18",
    "force_no_think": False,
}
]

In [96]:
%load_ext autoreload
%autoreload 2
    
import cga_utils
cga_utils.setups_summary(setups)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

,Model,Prompt,Item count:,Exact Match:,Value Match:,Time:
0,qwen3:4b,V11,497,53.72,69.62,0:00:03.515346
1,qwen3:4b,V18,497,59.96,75.65,0:00:03.179878
2,llama3.2:3b,V11,497,30.58,40.44,0:00:24.162917
3,llama3.2:3b,V18,497,22.33,32.60,0:12:21.546717
4,mistral,V11,497,17.91,21.33,0:13:36.880840
5,mistral,V18,497,41.45,42.66,0:19:35.650964
6,gemma3:4b,V11,497,34.81,55.53,0:25:52.908262
7,gemma3:4b,V18,497,42.66,56.74,0:42:58.292539
8,gemma3n:e4b,V11,497,29.78,48.49,0:45:45.701323
9,gemma3n:e4b,V18,497,42.05,54.73,1:11:07.946870
10,llama3.2:1b,V11,497,1.01,4.63,0:33:50.887506
11,gemma3:1b,V11,497,1.21,2.82,0:12:57.692094
12,qwen3:1.7b,V11,497,18.91,27.77,0:26:56.605246
13,qwen3:4b,V18,497,59.96,75.65,0:00:03.179878

In [97]:
def calc_t_stats(res1,res2, cname):
    complex_correct = res1[cname].astype(int)
    simple_correct = res2[cname].astype(int)
    
    # Paired t-test
    t_stat, p_value = stats.ttest_rel(simple_correct, complex_correct)
    
    print(f"t-statistic: {t_stat:.4f}")
    print(f"p-value: {p_value:.6f}")
    
    # Szignifikancia ellenőrzése 5%-os szinten
    if p_value < 0.05:
        print("Significant difference between prompts.")
    else:
        print("No significant difference between prompts.")

# Prompt lengh (complex/simple) based

In [93]:
import pandas as pd
from scipy import stats

setups_df = pd.DataFrame(setups)
models = [m for m in set(setups_df["model"]) if ':1' not in m]
for model in models:
    print(model)
    comp_df = pd.read_csv(f"res/ollama__{model.replace(':','_')}__V11.csv")
    simp_df = pd.read_csv(f"res/ollama__{model.replace(':','_')}__V18.csv")
    calc_t_stats(comp_df, simp_df, "exact_match")    
    calc_t_stats(comp_df, simp_df, "value_match")
    print('---')

gemma3n:e4b
t-statistic: 5.9896
p-value: 0.000000
Significant difference between prompts.
t-statistic: 3.3979
p-value: 0.000734
Significant difference between prompts.
---
gemma3:4b
t-statistic: 3.3416
p-value: 0.000896
Significant difference between prompts.
t-statistic: 0.5937
p-value: 0.552983
No significant difference between prompts.
---
mistral
t-statistic: 9.8976
p-value: 0.000000
Significant difference between prompts.
t-statistic: 9.4566
p-value: 0.000000
Significant difference between prompts.
---
llama3.2:3b
t-statistic: -3.8426
p-value: 0.000138
Significant difference between prompts.
t-statistic: -3.6184
p-value: 0.000327
Significant difference between prompts.
---
qwen3:4b
t-statistic: 3.3577
p-value: 0.000846
Significant difference between prompts.
t-statistic: 3.8004
p-value: 0.000162
Significant difference between prompts.
---

# Rule based

In [152]:
v18 = pd.read_csv('res/e38_18.csv')
v18r = pd.read_csv('res/e38_18r.csv')
v19 = pd.read_csv('res/e38_19.csv')
v19r = pd.read_csv('res/e38_19r.csv')
v20 = pd.read_csv('res/e38_20.csv')
v21 = pd.read_csv('res/e38_21.csv')
v22 = pd.read_csv('res/e38_22.csv')
v24 = pd.read_csv('res/e38_24.csv') # csak perc subtr added

v23 = pd.read_csv('res/e38_23.csv') # csak scale

v34 = pd.read_csv('res/e38_34.csv')

In [91]:
import pprint
print('prompt v18-v19')
calc_t_stats(v18,v19, "exact_match")
ds = diff_summary(v18,v19, "exact_match")
print(ds["n_questions"],ds["n_positive_diff"], ds["n_negative_diff"])
print('---')
print('prompt v19-v20')
calc_t_stats(v19,v20, "exact_match")
ds = diff_summary(v19,v20, "exact_match")
print(ds["n_questions"],ds["n_positive_diff"], ds["n_negative_diff"])
print('---')
print('prompt v18-v19')
calc_t_stats(v20,v21, "exact_match")
ds = diff_summary(v20,v21, "exact_match")
print(ds["n_questions"],ds["n_positive_diff"], ds["n_negative_diff"])
print('---')
calc_t_stats(v21,v22, "exact_match")
ds = diff_summary(v21,v22, "exact_match")
print(ds["n_questions"],ds["n_positive_diff"], ds["n_negative_diff"])
print('---')
calc_t_stats(v22,v24, "exact_match")
ds = diff_summary(v22,v24, "exact_match")
print(ds["n_questions"],ds["n_positive_diff"], ds["n_negative_diff"])
print('---')
print('---')
calc_t_stats(v18,v23, "exact_match")
ds = diff_summary(v18,v23, "exact_match")
print(ds["n_questions"],ds["n_positive_diff"], ds["n_negative_diff"])

t-statistic: 0.8833
p-value: 0.377525
No significant difference between prompts.
497 45 37
---
t-statistic: -0.9112
p-value: 0.362650
No significant difference between prompts.
497 26 33
---
t-statistic: -0.2826
p-value: 0.777616
No significant difference between prompts.
497 24 26
---
t-statistic: 3.5383
p-value: 0.000441
Significant difference between prompts.
497 61 28
---
t-statistic: 0.5219
p-value: 0.602007
No significant difference between prompts.
497 18 15
---
---
t-statistic: 2.4723
p-value: 0.013759
Significant difference between prompts.
497 51 29

In [90]:
def diff_summary(res1, res2, cname):
    diff = res2[cname].astype(int)-  res1[cname].astype(int)
    
    # Összesítés
    summary = {
        "n_questions": len(diff),
        "n_positive_diff": (diff > 0).sum(),    # egyszerű prompt jobb
        "n_negative_diff": (diff < 0).sum(),    # komplex prompt jobb
        "n_equal": (diff == 0).sum(),           # nincs különbség
        "mean_diff": diff.mean(),
        "std_diff": diff.std(ddof=1),
        "prop_positive": (diff > 0).mean()      # arány, amikor az egyszerű prompt jobb
    }
    return summary

In [1]:
import pandas as pd

def compare_success(
    df1: pd.DataFrame,
    df2: pd.DataFrame,
    key: str,
    flag: str,
    extra_cols=None
) -> pd.DataFrame:
    """
    Két DataFrame összehasonlítása kulcs és egy boolean flag alapján.
    Eredmény: df1 + 'change' + success_new + minden extra oszlop mindkét értékkel: <col>_old, <col>_new.

    - change: 'jobb lett' (False->True), 'rosszabb lett' (True->False), 'nem változott', vagy 'nincs összehasonlítás'
    - success_new: df2 flag értéke (ha nincs pár, NaN)
    - <col>_old: df1 érték
    - <col>_new: df2 érték
    """
    if extra_cols is None:
        extra_cols = []

    # df2: csak a szükséges oszlopok + átnevezés _new végződésre
    df2_keep = [key, flag] + list(extra_cols)
    df2_tmp = df2[df2_keep].copy()
    rename_map = {flag: f"{flag}_new"}
    rename_map.update({c: f"{c}_new" for c in extra_cols})
    df2_tmp.rename(columns=rename_map, inplace=True)

    # df1: készítsünk _old oszlopokat az extra oszlopoknak (ami nincs df1-ben, az NaN lesz)
    df1_tmp = df1.copy()
    for c in extra_cols:
        df1_tmp[f"{c}_old"] = df1_tmp[c] if c in df1_tmp.columns else pd.NA

    # merge (LEFT: df1 a bázis)
    merged = df1_tmp.merge(df2_tmp, on=key, how="left")

    # change oszlop
    def change_label(old, new):
        if pd.isna(new):
            return "UNPAIRED"
        if old == new:
            return "UNCHANGED"
        if old is False and new is True:
            return "FIXED"
        if old is True and new is False:
            return "BROKEN"
        return "UNKNOWN"

    merged["change"] = merged.apply(lambda r: change_label(r[flag], r.get(f"{flag}_new")), axis=1)

    # Rendezés: kulcs, flag(=old), flag_new, change, extra cols párok, majd df1 többi oszlop
    # (nem kötelező, csak olvashatóbb)
    cols_front = [key, flag, f"{flag}_new", "change"]
    extra_pairs = [x for col in extra_cols for x in (f"{col}_old", f"{col}_new")]
    other_cols = [c for c in merged.columns if c not in set(cols_front + extra_pairs)]
    ordered = cols_front + extra_pairs + other_cols

    return merged[ordered]
compare_success(v22, v24, "qid", "exact_match", ["error_code"]).to_csv('res/comp_v22_v24.csv')

NameError: name 'v22' is not defined

In [151]:
compare_success(v18, v18r, "qid", "exact_match", ["error_code"]).to_csv('res/comp_v18_v18r.csv')

In [114]:
pairs=[
    ("V18", "V19"), #add avg
    #("V19", "V21r"), #add avg diff DROPPED
    ("V19", "V22r"), # scale added
    ("V22r", "V29"), # substraction added
    ("V29", "V25"), # index added DROPPED
    ("V29", "V31"), # all years added DROPPED
    ("V29", "V32"), # avg diff added DROPPED
]

v18 = pd.read_csv('res/e38_18.csv')
v19 = pd.read_csv('res/e38_19.csv')
v19r = pd.read_csv('res/e38_19r.csv')
v20 = pd.read_csv('res/e38_20.csv')
v21 = pd.read_csv('res/e38_21.csv')
v22 = pd.read_csv('res/e38_22.csv')
v22r = pd.read_csv('res/e38_22r.csv')
v24 = pd.read_csv('res/e38_24.csv') 
v25 = pd.read_csv('res/e38_25.csv') 
v29 = pd.read_csv('res/e38_29.csv') 
v31 = pd.read_csv('res/e38_31.csv') 
v32 = pd.read_csv('res/e38_32.csv')

In [115]:
print('prompt v18-v19')
calc_t_stats(v18,v19, "exact_match")
ds = diff_summary(v18,v19, "exact_match")
print(ds["n_questions"],ds["n_positive_diff"], ds["n_negative_diff"])
print('---')
print('prompt v19-v22r')
calc_t_stats(v19,v22r, "exact_match")
ds = diff_summary(v19,v22r, "exact_match")
print(ds["n_questions"],ds["n_positive_diff"], ds["n_negative_diff"])
print('---')
print('prompt v22r-v29')
calc_t_stats(v22r,v29, "exact_match")
ds = diff_summary(v22r,v29, "exact_match")
print(ds["n_questions"],ds["n_positive_diff"], ds["n_negative_diff"])
print('---')
print('prompt v29-v25')
calc_t_stats(v29,v25, "exact_match")
ds = diff_summary(v29,v25, "exact_match")
print(ds["n_questions"],ds["n_positive_diff"], ds["n_negative_diff"])
print('---')
print('prompt v29-v31')
calc_t_stats(v29,v31, "exact_match")
ds = diff_summary(v29,v31, "exact_match")
print(ds["n_questions"],ds["n_positive_diff"], ds["n_negative_diff"])
print('---')
print('prompt v29-v32')
calc_t_stats(v29,v32, "exact_match")
ds = diff_summary(v29,v32, "exact_match")
print(ds["n_questions"],ds["n_positive_diff"], ds["n_negative_diff"])

prompt v18-v19
t-statistic: 0.8833
p-value: 0.377525
No significant difference between prompts.
497 45 37
---
prompt v19-v22r
t-statistic: 4.1419
p-value: 0.000040
Significant difference between prompts.
497 57 21
---
prompt v22r-v29
t-statistic: 1.5690
p-value: 0.117285
No significant difference between prompts.
497 21 12
---
prompt v29-v25
t-statistic: -0.5996
p-value: 0.549038
No significant difference between prompts.
497 11 14
---
prompt v29-v31
t-statistic: -0.6663
p-value: 0.505533
No significant difference between prompts.
497 16 20
---
prompt v29-v32
t-statistic: -1.6191
p-value: 0.106065
No significant difference between prompts.
497 11 20

In [116]:
import rules_stats
dec = rules_stats.rule_gate_decision(
    v18, v19,
    alpha=0.05,
    min_delta_pp=0.5,        # legalább +0.5 százalékpont ΔEM
    use_bootstrap=True,      # 95% CI ne tartalmazza a 0-t
    use_permutation=True,    # permutációs p<alpha
    require_variants=False   # ha van variant oszlopod és stabilitást is kérsz, állítsd True-ra
)
print(dec.accepted, dec.reason)
print(dec.summary)

False McNemar p>=alpha vagy ΔEM túl kicsi; bootstrap CI tartalmazza a 0-t; permutációs p>=alpha
{'N': 497, 'b_improved': 45, 'c_degraded': 37, 'delta_pp': 1.6096579476861161, 'p_mcnemar_exact': 0.439705429185822, 'p_mcnemar_chi2cc': 0.4395101404445545, 'criteria': {'mcnemar_and_delta': False, 'bootstrap_CI_excludes_0': False, 'perm_test': False}, 'bootstrap': {'delta_point': 1.6096579476861161, 'ci_low': -2.012072434607648, 'ci_high': 5.231388329979869}, 'permutation': {'delta_point': 1.6096579476861161, 'p_value': 0.43875612438756123}}

In [117]:
import rules_stats
dec = rules_stats.rule_gate_decision(
    v18, v19r,
    alpha=0.05,
    min_delta_pp=0.5,        # legalább +0.5 százalékpont ΔEM
    use_bootstrap=True,      # 95% CI ne tartalmazza a 0-t
    use_permutation=True,    # permutációs p<alpha
    require_variants=False   # ha van variant oszlopod és stabilitást is kérsz, állítsd True-ra
)
print(dec.accepted, dec.reason)
print(dec.summary)

False McNemar p>=alpha vagy ΔEM túl kicsi; bootstrap CI tartalmazza a 0-t; permutációs p>=alpha
{'N': 497, 'b_improved': 40, 'c_degraded': 31, 'delta_pp': 1.810865191146871, 'p_mcnemar_exact': 0.34247099841986794, 'p_mcnemar_chi2cc': 0.3424043343095283, 'criteria': {'mcnemar_and_delta': False, 'bootstrap_CI_excludes_0': False, 'perm_test': False}, 'bootstrap': {'delta_point': 1.810865191146871, 'ci_low': -1.810865191146871, 'ci_high': 5.231388329979881}, 'permutation': {'delta_point': 1.810865191146871, 'p_value': 0.3504649535046495}}

In [119]:

dec = rules_stats.rule_gate_decision(v19, v22r, alpha=0.05, min_delta_pp=0.5, use_bootstrap=True, use_permutation=True)
print(dec.accepted, dec.reason)
print(dec.summary)

True OK
{'N': 497, 'b_improved': 57, 'c_degraded': 21, 'delta_pp': 7.2434607645875175, 'p_mcnemar_exact': 5.5711164864691095e-05, 'p_mcnemar_chi2cc': 7.402320460148104e-05, 'criteria': {'mcnemar_and_delta': True, 'bootstrap_CI_excludes_0': True, 'perm_test': True}, 'bootstrap': {'delta_point': 7.2434607645875175, 'ci_low': 3.82293762575453, 'ci_high': 10.663983903420526}, 'permutation': {'delta_point': 7.2434607645875175, 'p_value': 9.999000099990002e-05}}

In [120]:

dec = rules_stats.rule_gate_decision(v22r, v29, alpha=0.05, min_delta_pp=0.5, use_bootstrap=True, use_permutation=True)
print(dec.accepted, dec.reason)
print(dec.summary)

False McNemar p>=alpha vagy ΔEM túl kicsi; bootstrap CI tartalmazza a 0-t; permutációs p>=alpha
{'N': 497, 'b_improved': 21, 'c_degraded': 12, 'delta_pp': 1.810865191146882, 'p_mcnemar_exact': 0.16275565745308995, 'p_mcnemar_chi2cc': 0.16373435432459205, 'criteria': {'mcnemar_and_delta': False, 'bootstrap_CI_excludes_0': False, 'perm_test': False}, 'bootstrap': {'delta_point': 1.810865191146882, 'ci_low': -0.4024144869215318, 'ci_high': 4.024144869215296}, 'permutation': {'delta_point': 1.810865191146882, 'p_value': 0.15428457154284572}}

In [123]:
# Példa: minden futásnál van egy df: columns = ["question_id", "em"]
# és tudod, mely szabályok voltak ON (True/False)

#v18: no rule
#v19: year avg  rule1
#V22r: scale added rule2
#v29: ubstraction added rule3
#v25: no index added rule 4
#v31: all years added DROPPED rule 5
#v32: year avg diff added DROPPED rule 6

runs = [
    # (df, dict of active rules, run_id)
    #(v18, {"rule1": False,  "rule2": False, "rule3": False, "rule4": False, "rule5": False, "rule6": False}, "V0_baseline"),
    (v19, {"rule1": True,  "rule2": False, "rule3": False, "rule4": False, "rule5": False, "rule6": False}, "V1_rule1"),
    (v22r, {"rule1": True,  "rule2": True, "rule3": False, "rule4": False, "rule5": False, "rule6": False}, "V2_rule1_rule2"),
    (v29, {"rule1": True,  "rule2": True, "rule3": True, "rule4": False, "rule5": False, "rule6": False}, "V3_rule1_rule2_rule3"),
    (v25, {"rule1": True,  "rule2": True, "rule3": True, "rule4": True, "rule5": False, "rule6": False}, "V4_rule1_rule2_rule3_rule4"),
    (v31, {"rule1": True,  "rule2": True, "rule3": True, "rule4": False, "rule5": True, "rule6": False}, "V5_rule1_rule2_rule3_rule_5"),
    (v32, {"rule1": True,  "rule2": True, "rule3": True, "rule4": False, "rule5": False, "rule6": True}, "V6_rule1_rule2_rule3_rule6"),
    
    #(result2_df, {"rule1": True,  "rule2": True,  "rule3": False}, "V2_rule1_rule2"),
    #(result3_df, {"rule1": True,  "rule2": True,  "rule3": True }, "V3_rule1_rule2_rule3"),
    # stb.
]

# szabályok listája (rendezett, konzisztens oszlopnév)
rules = ["rule1","rule2","rule3","rule4","rule5","rule6"]

long_parts = []
for df, rules_on, run_id in runs:
    tmp = df.copy()
    tmp["run_id"] = run_id
    for r in rules:
        tmp[r] = bool(rules_on.get(r, False))
    long_parts.append(tmp)

long_df = pd.concat(long_parts, ignore_index=True)

# Ellenőrzés
# long_df oszlopok: question_id, em (0/1), run_id, rule1..ruleN
print(long_df.head())

   Unnamed: 0                                   qid  \
0           0  b2786c1a-37de-4120-b03c-32bf5c81f157
1           1  fe11f001-3bfe-4089-8108-412676f0a780
2           2  5103aed0-b4e8-4fae-bf78-e2c9f4ba84cf
3           3  4dc8be43-d8d9-4b08-9ffd-9c19012361ce
4           4  6c44a1a8-0785-43a0-90ab-7e21df2c57d9

                                            question           derivation  \
0  What was the change in the amount for Applianc...              680-774
1  What was the percentage change in the amount f...        (680-774)/774
2  What is the difference between the domestic an...         4.00 - 1.90
3  What is the year on year percentage change in ...  (4.00 - 3.75)/3.75
4  What is the year on year percentage change in ...  (3.40 - 3.70)/3.70

  calc_pattern   pred pred_scale  answer    scale  value_match  ...  \
0          #-# -94.00    million  -94.00  million         True  ...
1      (#-#)/# -12.14    percent  -12.14  percent         True  ...
2          #-#   2.10    percent    2.10  percent         True  ...
3      (#-#)/#   6.67    percent    6.67  percent         True  ...
4      (#-#)/#  -8.11    percent   -8.11  percent         True  ...

   exact_match  error_code    run_id  rule1  rule2  rule3  rule4  rule5  \
0         True        none  V1_rule1   True  False  False  False  False
1         True        none  V1_rule1   True  False  False  False  False
2         True        none  V1_rule1   True  False  False  False  False
3         True        none  V1_rule1   True  False  False  False  False
4         True        none  V1_rule1   True  False  False  False  False

   rule6  ts
0  False NaN
1  False NaN
2  False NaN
3  False NaN
4  False NaN

[5 rows x 29 columns]

In [127]:
import statsmodels.api as sm
import statsmodels.formula.api as smf
import numpy as np

long_df["em"] = long_df["exact_match"].astype(int) 

formula = "em ~ " + " + ".join(rules)
gee = smf.gee(
    formula=formula,
    groups="qid",             # kérdés azonosító mint klaszter
    data=long_df,
    family=sm.families.Binomial(),
    cov_struct=sm.cov_struct.Exchangeable()
).fit()

print(gee.summary())

# Odds ratio és 95% CI a szabályokra
params = gee.params
conf = gee.conf_int()
or_ci = np.exp(pd.DataFrame({"OR": params, "CI_low": conf[0], "CI_high": conf[1]}))
print("\nOdds ratios (rules):\n", or_ci.loc[rules])

                               GEE Regression Results
===================================================================================
Dep. Variable:                          em   No. Observations:                 2982
Model:                                 GEE   No. clusters:                      497
Method:                        Generalized   Min. cluster size:                   6
                      Estimating Equations   Max. cluster size:                   6
Family:                           Binomial   Mean cluster size:                 6.0
Dependence structure:         Exchangeable   Num. iterations:                    60
Date:                     Tue, 19 Aug 2025   Scale:                           1.000
Covariance type:                    robust   Time:                         13:54:38
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept      3.694e+12      0.046      8e+13      0.000    3.69e+12    3.69e+12
rule1[T.True] -3.694e+12      0.046     -8e+13      0.000   -3.69e+12   -3.69e+12
rule2[T.True]     0.3207      0.078      4.125      0.000       0.168       0.473
rule3[T.True]     0.0860      0.055      1.568      0.117      -0.021       0.194
rule4[T.True]    -0.0290      0.048     -0.600      0.548      -0.124       0.066
rule5[T.True]    -0.0386      0.058     -0.667      0.505      -0.152       0.075
rule6[T.True]    -0.0861      0.053     -1.620      0.105      -0.190       0.018
==============================================================================
Skew:                         -0.7911   Kurtosis:                      -1.3533
Centered skew:                -1.1825   Centered kurtosis:              7.1651
==============================================================================

/home/apandy/environemnts/tabular39/lib/python3.9/site-packages/statsmodels/genmod/generalized_estimating_equations.py:1300: IterationLimitWarning: Iteration limit reached prior to convergence
  warnings.warn("Iteration limit reached prior to convergence",
/home/apandy/environemnts/tabular39/lib/python3.9/site-packages/pandas/core/internals/blocks.py:329: RuntimeWarning: overflow encountered in exp
  result = func(self.values, **kwargs)

KeyError: "None of [Index(['rule1', 'rule2', 'rule3', 'rule4', 'rule5', 'rule6'], dtype='object')] are in the [index]"

In [129]:
long_df["em"].value_counts()

em
1    2042
0     940
Name: count, dtype: int64

In [125]:
or_ci

                     OR    CI_low   CI_high
Intercept      0.786697  0.718657  0.861179
rule1[T.True]  0.786697  0.718657  0.861179
rule2[T.True]  0.725456  0.622925  0.844865
rule3[T.True]  0.917485  0.823968  1.021614
rule4[T.True]  1.029463  0.936331  1.131859
rule5[T.True]  1.039398  0.927819  1.164394
rule6[T.True]  1.089937  0.982103  1.209610

# Local Effects

In [144]:
#v19
def local_effect(res1, res2, error_code, calc_pattern):
    target_group_qids = list(res1.query(f"error_code == '{error_code}' and calc_pattern == '{calc_pattern}'")["qid"])
    post_df = res2
    target_group_post = post_df[post_df["qid"].isin(target_group_qids)]
    print('EM pre: ', cga_utils.calc_overall_em(target_group_pre), "EM post: ",cga_utils.calc_overall_em(target_group_post))
    #calc_t_stats(target_group_pre, target_group_pre, "exact_match")
    dec = rules_stats.rule_gate_decision(res1, res2, alpha=0.05, min_delta_pp=0.5, use_bootstrap=True, use_permutation=True)
    print(dec.accepted, dec.reason)
    print(dec.summary)
local_effect(v18, v19, "scale_error", "(#-#)/#")

EM pre:  0.0 EM post:  0.4444444444444444
False McNemar p>=alpha vagy ΔEM túl kicsi; bootstrap CI tartalmazza a 0-t; permutációs p>=alpha
{'N': 497, 'b_improved': 45, 'c_degraded': 37, 'delta_pp': 1.6096579476861161, 'p_mcnemar_exact': 0.439705429185822, 'p_mcnemar_chi2cc': 0.4395101404445545, 'criteria': {'mcnemar_and_delta': False, 'bootstrap_CI_excludes_0': False, 'perm_test': False}, 'bootstrap': {'delta_point': 1.6096579476861161, 'ci_low': -2.012072434607648, 'ci_high': 5.231388329979869}, 'permutation': {'delta_point': 1.6096579476861161, 'p_value': 0.43875612438756123}}

In [147]:
local_effect(v22r, v22r, "scale_error", "(#-#)/#")

EM pre:  0.0 EM post:  0.0
False McNemar p>=alpha vagy ΔEM túl kicsi; bootstrap CI tartalmazza a 0-t; permutációs p>=alpha
{'N': 497, 'b_improved': 0, 'c_degraded': 0, 'delta_pp': 0.0, 'p_mcnemar_exact': 1.0, 'p_mcnemar_chi2cc': 1.0, 'criteria': {'mcnemar_and_delta': False, 'bootstrap_CI_excludes_0': False, 'perm_test': False}, 'bootstrap': {'delta_point': 0.0, 'ci_low': 0.0, 'ci_high': 0.0}, 'permutation': {'delta_point': 0.0, 'p_value': 1.0}}

In [146]:
target_group_pre

,Unnamed: 0,qid,question,derivation,calc_pattern,pred,pred_scale,answer,scale,value_match,...,is_parenth_in_table,has_code_abs,error_text,value_list,code,selected_values,needed_values,exact_match,error_code,aggr_calc_pattern
31,31,58adf6c4-41ae-4f3f-84cb-cf3469a80ce4,What was the percentage change in Total Other ...,($166.3-$513.3)/$513.3,(#-#)/#,-67.60,million,-67.60,percent,True,...,False,False,NaN,"[{'number_value': 94.2, 'scale': '', 'category...",def run(value_list):\n for item in value_li...,"[166.3, 513.3, -67.60179232417688]","[166.3, 513.3, 513.3]",False,scale_error,(#-#)/#
54,54,3b5bb347-41c7-499a-b044-87b9a04b0833,What was the percentage change in Total Other ...,(95-82)/82,(#-#)/#,15.85,NaN,15.85,percent,True,...,False,False,NaN,"[{'number_value': 614493.0, 'scale': '', 'cate...",def run(value_list):\n total_other_2018 = n...,"[95.0, 82.0, 15.853658536585366]","[95.0, 82.0, 82.0]",False,scale_error,(#-#)/#
67,67,8a21f821-eaf6-421a-8c67-795e7e2d1f61,What was the percentage change in Adjusted EBI...,"(108,307-93,081)/93,081",(#-#)/#,16.36,NaN,16.36,percent,True,...,True,False,NaN,"[{'number_value': 53330.0, 'scale': '', 'categ...",def run(value_list):\n adjusted_ebitda_2019...,"[108307.0, 93081.0, 16.357795898196194]","[108307.0, 93081.0, 93081.0]",False,scale_error,(#-#)/#
68,68,07ec204e-3922-4b5c-b1fd-9cb9311a53e5,What was the percentage change in the Total ne...,"(14,158-18,211)/18,211",(#-#)/#,-22.26,NaN,-22.26,percent,True,...,True,False,NaN,"[{'number_value': 19795.0, 'scale': '', 'categ...",def run(value_list):\n total_net_deferred_t...,"[18211.0, 14158.0, -22.25577947394432]","[14158.0, 18211.0, 18211.0]",False,scale_error,(#-#)/#
71,71,cc053817-3496-48b3-9bfc-83e9ba71bb57,What is the percentage increase in the number ...,"(10,692,594 - 6,737,076)/6,737,076",(#-#)/#,58.71,NaN,58.71,percent,True,...,True,False,NaN,"[{'number_value': 10692594.0, 'scale': '', 'ca...",def run(value_list):\n # Extract outstandin...,"[6737076.0, 10692594.0, 58.712681881575925]","[10692594.0, 6737076.0, 6737076.0]",False,scale_error,(#-#)/#
86,86,0f45cc67-fd57-4930-a0d0-f5d7174d7562,What is the percentage change in the value of ...,(222 - 191)/191,(#-#)/#,16.23,thousand,16.23,percent,True,...,True,False,NaN,"[{'number_value': 222.0, 'scale': 'thousand', ...",def run(value_list):\n # Filter for raw mat...,"[222.0, 191.0, 16.230366492146597]","[222.0, 191.0, 191.0]",False,scale_error,(#-#)/#
87,87,a30ab3a2-f930-4bf4-9b52-35c9c504d992,What is the percentage change in the value of ...,"(2,370 - 2,929)/2,929",(#-#)/#,-19.09,thousand,-19.09,percent,True,...,True,False,NaN,"[{'number_value': 222.0, 'scale': 'thousand', ...",def run(value_list):\n # Filter for work-in...,"[2370.0, 2929.0, -19.08501194947081]","[2370.0, 2929.0, 2929.0]",False,scale_error,(#-#)/#
88,88,7df5635a-6f79-4fd2-8dc4-a5040e04cf4c,What is the percentage change in the value of ...,(668 - 716)/716,(#-#)/#,-6.70,thousand,-6.70,percent,True,...,True,False,NaN,"[{'number_value': 222.0, 'scale': 'thousand', ...",def run(value_list):\n # Filter for finishe...,"[668.0, 716.0, -6.70391061452514]","[668.0, 716.0, 716.0]",False,scale_error,(#-#)/#
106,106,b11567d3-d651-40d8-9b9e-bc71eb37d7f9,What was the percentage change in Transportati...,(613-636)/636,(#-#)/#,-3.62,NaN,-3.62,percent,True,...,False,False,NaN,"[{'number_value': 1949.0, 'scale': '', 'catego...",def run(value_list):\n # Filter for Transpo...,"[636.0, 613.0, -3.62]","[613.0, 636.0, 636.0]",False,scale_error,(#-#)/#
113,113,775c21fd-9c4c-44d7-9879-81c2ca6d2420,What was the percentage change in cash and cas...,"(9,472-7,554)/7,554",(#-#)/#,25.39,thousand,25.39,percent,True,...,True,False,NaN,"[{'number_value': 9472.0, 'scale': 'thousand',...",def run(value_list):\n cash_2019 = next(ite...,"[9472.0, 7554.0, 25.390521577971935]","[9472.0, 7554.0, 7554.0]",False,scale_error,(#-#)/#
182,182,e172ba38-34fa-477b-b535-bac8d65756fb,What is the percentage change in revenues from...,"(68,024-67,314)/67,314",(#-#)/#,1.05,thousand,1.05,percent,True,...,False,False,NaN,"[{'number_value': 68024.0, 'scale': 'thousand'...",def run(value_list):\n revenues_2019 = next...,"[68024.0, 67314.0, 1.0547582969367442]","[68024.0, 67314.0, 67314.0]",False,scale_error,(#-#)/#
227,227,8c6bc2ca-b758-49f8-82e3-c1ede110102b,What is the percentage change in the amounts o...,(0.1-0.1)/0.1,(#-#)/#,-0.00,percent,0.00,percent,True,...,False,False,NaN,"[{'number_value': 0.8, 'scale': 'million', 'ca...",def run(value_list):\n for item in value_li...,"[-0.1, -0.1]",[],False,scale_error,(#-#)/#
252,252,8cf06f37-dccd-4b16-8f75-5359a9a55d93,What was the percentage change in the average ...,(86.8-87.3)/87.3,(#-#)/#,-0.57,NaN,-0.57,percent,True,...,False,False,NaN,"[{'number_value': 86.8, 'scale': '', 'category...",def run(value_list):\n # Find the 2019 valu...,"[86.8, 87.3, -0.5727376861397481]","[86.8, 87.3, 87.3]",False,scale_error,(#-#)/#
256,256,0f59d1f7-562f-4f9a-a0ff-1abba61accbe,What was the percentage change in the Total am...,(44.5-41.0)/41.0,(#-#)/#,8.54,million,8.54,percent,True,...,False,False,NaN,"[{'number_value': 45.4, 'scale': 'million', 'c...",def run(value_list):\n total_2019 = next(it...,"[44.5, 41.0, 8.536585365853659]","[44.5, 41.0, 41.0]",False,scale_error,(#-#)/#
273,273,22ea63c7-2e41-48d8-8133-1fd9acebbb5b,What is the percentage change in the total fai...,"(3,777 - 3,757)/3,757",(#-#)/#,0.53,NaN,0.53,percent,True,...,True,False,NaN,"[{'number_value': 3795.0, 'scale': '', 'catego...",def run(value_list):\n estimated_june = nex...,"[3757.0, 3777.0, 0.5323396326856534]","[3777.0, 3757.0, 3757.0]",False,scale_error,(#-#)/#
283,283,24395900-adc1-4c9d-8ce9-bd21c5a54808,What was the percentage change in Net income a...,"($1,887.8-$1,236.4)/$1,236.4",(#-#)/#,52.69,million,52.69,percent,True,...,True,False,NaN,"[{'number_value': 1887.8, 'scale': '', 'catego...",def run(value_list):\n for item in value_li...,"[1887.8, 1236.4, 52.685215140731145]","[1887.8, 1236.4, 1236.4]",False,scale_error,(#-#)/#
284,284,d1e84439-5663-4c28-9d59-3854a0104409,What is the percentage increase in cash provid...,"(1,389 - 1,779) / 1,779",(#-#)/#,-21.92,NaN,-21.92,percent,True,...,True,False,NaN,"[{'number_value': -618.0, 'scale': '', 'catego...",def run(value_list):\n # Filter values for ...,"[1779.0, 1389.0, -21.922428330522767]","[1389.0, 1779.0, 1779.0]",False,scale_error,(#-#)/#
285,285,6befb6ea-a586-43d2-80bd-14f0721dd6f1,What is the percentage change in the total oth...,"(41,846 - 8,620)/8,620",(#-#)/#,385.45,NaN,385.45,percent,True,...,False,False,NaN,"[{'number_value': 33014.0, 'scale': '', 'categ...",def run(value_list):\n total_2019 = next(it...,"[41846.0, 8620.0, 385.4524361948956]","[41846.0, 8620.0, 8620.0]",False,scale_error,(#-#)/#
294,294,070a9fb1-6d17-40ba-b34e-82d0fe14037b,What is the percentage change in the research ...,"(18,478-17,793)/17,793",(#-#)/#,3.85,NaN,3.85,percent,True,...,False,False,NaN,"[{'number_value': 244.0, 'scale': '', 'categor...",def run(value_list):\n for item in value_li...,"[18478.0, 17793.0, 3.849828584274715]","[18478.0, 17793.0, 17793.0]",False,scale_error,(#-#)/#
296,296,9fce8f25-dd3b-4c50-9b7b-d200ced15ded,What is the percentage change in the finance c...,(200-62)/62,(#-#)/#,222.58,NaN,222.58,percent,True,...,False,False,NaN,"[{'number_value': 244.0, 'scale': '', 'categor...",def run(value_list):\n finance_costs_2019 =...,"[200.0, 62.0, 222.5806451612903]","[200.0, 62.0, 62.0]",False,scale_error,(#-#)/#
298,298,06dfc869-b3e2-446e-9b9a-1b2374c63c04,What is the percentage change in cash provided...,"(5,798-3,624)/3,624",(#-#)/#,59.99,NaN,59.99,percent,True,...,True,False,NaN,"[{'number_value': -426.0, 'scale': '', 'catego...",def run(value_list):\n # Filter for financi...,"[3624.0, 5798.0, 59.98896247240618]","[5798.0, 3624.0, 3624.0]",False,scale_error,(#-#)/#
303,303,0a9b94be-b354-46e2-a448-e68b5f9f5e92,What is the percentage change of net operating...,"(113,475-61,494)/61,494",(#-#)/#,84.53,NaN,84.53,percent,True,...,True,False,NaN,"[{'number_value': 113475.0, 'scale': '', 'cate...",def run(value_list):\n # Filter for net ope...,"[61494.0, 113475.0, 84.5301980681042]","[113475.0, 61494.0, 61494.0]",False,scale_error,(#-#)/#
315,315,c48a89ed-da90-4c07-b51e-2e77b5817f3d,What was the percentage change in Transportati...,"(4,781-4,707)/4,707",(#-#)/#,1.57,million,1.57,percent,True,...,False,False,NaN,"[{'number_value': 4781.0, 'scale': 'million', ...",def run(value_list):\n transport_2019 = nex...,"[4781.0, 4707.0, 1.5721266199277673]","[4781.0, 4707.0, 4707.0]",False,scale_error,(#-#)/#
320,320,6fbcd1ee-5060-442b-a2d2-8d62ac822942,What is the percentage change in the interim d...,"(14,801-13,099)/13,099",(#-#)/#,12.99,thousand,12.99,percent,True,...,True,False,NaN,"[{'number_value': 13327.0, 'scale': 'thousand'...",def run(value_list):\n for item in value_li...,"[14801.0, 13099.0, 12.993358271623789]","[14801.0, 13099.0, 13099.0]",False,scale_error,(#-#)/#
324,324,2b77bd1e-17ee-4f74-9fb7-7cc4ad5142dd,What is the percentage change in Other for def...,(577-553)/553,(#-#)/#,4.34,million,4.34,percent,True,...,True,False,NaN,"[{'number_value': 1169.0, 'scale': 'million', ...",def run(value_list):\n other_2019 = next(v[...,"[577.0, 553.0, 4.3399638336347195]","[577.0, 553.0, 553.0]",False,scale_error,(#-#)/#
336,336,5c487c82-e20a-4c76-9f52-7831ab15075e,What was the percentage change in the amount O...,"(3,104,563-2,682,738)/2,682,738",(#-#)/#,15.72,NaN,15.72,percent,True,...,True,False,NaN,"[{'number_value': 3104563.0, 'scale': '', 'cat...",def run(value_list):\n for item in value_li...,"[3104563.0, 2682738.0, 15.723674842642108]","[3104563.0, 2682738.0, 2682738.0]",False,scale_error,(#-#)/#
343,343,43e6bb90-dd1b-4f54-bdb7-60556312ad4e,What was the percentage change in the number o...,"(1,001.1-907.3)/907.3",(#-#)/#,10.34,NaN,10.34,percent,True,...,True,False,NaN,"[{'number_value': 2719.1, 'scale': '', 'catego...",def run(value_list):\n for item in value_li...,"[1001.1, 907.3, 10.338366582166877]","[1001.1, 907.3, 907.3]",False,scale_error,(#-#)/#
367,367,babee4bb-4861-4918-9a8e-dbadec47fe94,What was the percentage change in the amount O...,"(320,872-690,791)/690,791",(#-#)/#,-53.55,NaN,-53.55,percent,True,...,True,False,NaN,"[{'number_value': 690791.0, 'scale': '', 'cate...",def run(value_list):\n # Find the outstandi...,"[320872.0, 690791.0, -53.55006072748487]","[320872.0, 690791.0, 690791.0]",False,scale_error,(#-#)/#
369,369,040fbb37-ccac-4854-ad02-539c11a00b6f,What was the percentage change in in-game net ...,"($3,366-$4,203)/$4,203",(#-#)/#,-19.91,million,-19.91,percent,True,...,True,False,NaN,"[{'number_value': 6388.0, 'scale': '', 'catego...",def run(value_list):\n for item in value_li...,"[3366.0, 4203.0, -837.0, -19.914346895074946]","[3366.0, 4203.0, 4203.0]",False,scale_error,(#-#)/#
402,402,176587d4-2707-40ee-9bd5-cd2d75e17980,What is the percentage change in net income be...,"(53,294-61,431)/61,431",(#-#)/#,-13.25,NaN,-13.25,percent,True,...,True,False,NaN,"[{'number_value': 53294.0, 'scale': '', 'categ...",def run(value_list):\n # Filter net income ...,"[53294.0, 61431.0, -13.245755400367893]","[53294.0, 61431.0, 61431.0]",False,scale_error,(#-#)/#
409,409,bb5be96c-78ed-4453-92cc-d07a3bf0b6ff,What is the percentage change in net cash prov...,"($90,253-$67,510)/$67,510",(#-#)/#,33.69,NaN,33.69,percent,True,...,True,False,NaN,"[{'number_value': 115549.0, 'scale': '', 'cate...",def run(value_list):\n for item in value_li...,"[67510.0, 90253.0, 33.68834246778255]","[90253.0, 67510.0, 67510.0]",False,scale_error,(#-#)/#
410,410,058d1fa4-99b9-481d-a815-3c6df09cc031,What is the percentage change in the net cost ...,"(1,298-1,601)/1,601",(#-#)/#,-18.93,thousand,-18.93,percent,True,...,True,False,NaN,"[{'number_value': 672.0, 'scale': 'thousand', ...",def run(value_list):\n # Find the net cost ...,"[1298.0, 1601.0, -18.925671455340414]","[1298.0, 1601.0, 1601.0]",False,scale_error,(#-#)/#
413,413,bbf04869-c442-4909-a65d-c7bc89b6e726,What is the percentage increase in Swiss incom...,"($177,935 - $161,544) / $161,544",(#-#)/#,10.15,NaN,10.15,percent,True,...,False,False,NaN,"[{'number_value': 212986.0, 'scale': '', 'cate...",def run(value_list):\n swiss_2017 = next(v[...,"[161544.0, 177935.0, 16391.0, 10.146461645124548]","[177935.0, 161544.0, 161544.0]",False,scale_error,(#-#)/#
434,434,ac017bd6-9ee5-4d08-b96c-19fc5bb9d1ed,What is the percentage change in gross deferre...,"(38,771-38,721)/38,721",(#-#)/#,0.13,thousand,0.13,percent,True,...,True,False,NaN,"[{'number_value': 26.0, 'scale': 'thousand', '...",def run(value_list):\n for item in value_li...,"[38771.0, 38721.0, 0.1291288964644508]","[38771.0, 38721.0, 38721.0]",False,scale_error,(#-#)/#
475,475,12a99674-3d7b-43b8-acce-98a83bd7c70e,What is the percentage change of revenue from ...,"(1,761-1,429)/1,429",(#-#)/#,23.23,NaN,23.23,percent,True,...,False,False,NaN,"[{'number_value': 12451.0, 'scale': '', 'categ...",def run(value_list):\n # Filter values for ...,"[1429.0, 1761.0, 23.233030090972708]","[1761.0, 1429.0, 1429.0]",False,scale_error,(#-#)/#
480,480,890e40b2-3009-449f-b806-49d0a4fa82cd,What is the percentage change in the total bal...,"(3,933.5-2,623.7)/2,623.7",(#-#)/#,49.92,NaN,49.92,percent,True,...,True,False,NaN,"[{'number_value': 4565.4, 'scale': '', 'catego...",def run(value_list):\n # Find the total bal...,"[2623.7, 3933.5, 49.92186606700462]","[3933.5, 2623.7, 2623.7]",False,scale_error,(#-#)/#